name: bfpocket
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  curved_navigation_bar:
  flutter:
    sdk: flutter



  cupertino_icons: ^0.1.3
  mask_text_input_formatter: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
  - assets/logo.png
  - assets/icon.btn.login.png
  - assets/icon.btn.reg.png
  - assets/cadeado-recovery.png
  - assets/add.person.btn.png
  